### ISSUE TITLE
Client outdated

### ISSUE THREAD

**Issue by redlock** [heroiclabs/nakama-swift#12]
Hello,
Is there any plans to update swift SDK? 
We are considering using Nakama, however the lack of Nakama 2 support in Swift is stopping use from adopting it since most of our work is through iOS.
Thanks

**Comment by novabyte** [comment]
@redlock We've not had much demand for the Swift SDK so we deprioritized it until we could find a community collaborator/maintainer to collaborate on it. Is this something you'd be interested to do?

**Comment by redlock** [comment]
Unfortunately I am unable to contribute due to my own schedule. I have noticed that you guys maintain a C++ library. Is it possible to create Swift binding to this library (Using c wrappers)?

**Comment by novabyte** [comment]
We'd not gain much from a maintenance perspective. The update which needs to be made to this client is:

1. Update and re-generate service stubs for Swift with the latest GRPC-Swift compiler and runtime.
2. Update the sockets library or replace with a new one after a review of the options in the Swift community.
3. Modernize the code structure to fit with the latest practices in the Swift toolchain.

**Comment by Allan-Nava** [comment]
> We'd not gain much from a maintenance perspective. The update which needs to be made to this client is:
> 
> 1. Update and re-generate service stubs for Swift with the latest GRPC-Swift compiler and runtime.
> 2. Update the sockets library or replace with a new one after a review of the options in the Swift community.
> 3. Modernize the code structure to fit with the latest practices in the Swift toolchain.

Any news about these features?

**Comment by mofirouz** [comment]
The low-level client library (gRPC as well as realtime socket) has been updated to support Nakama 2 and Nakama 3. There are many gRPC wrapper functions missing from the implementation. Help is appreciated on this. I will close this in favor of #10.
