### ISSUE TITLE
Problem with Nakama.podspec 

### ISSUE THREAD

**Issue by Allan-Nava** [heroiclabs/nakama-swift#16]
This pod doesn't exist:

```podspec
  # Need to fix with https://github.com/apple/swift-atomics
  #s.dependency "Atomics", '~> 0.0.2', '< 0.0.3', :git => "https://github.com/apple/swift-atomics"
```

![image](https://user-images.githubusercontent.com/22498435/114384916-9fe2c680-9b8f-11eb-99d8-a51d5f5d1722.png)

**Comment by Allan-Nava** [comment]
It works only with swift package manager

<img width="1176" alt="Screenshot 2021-04-12 at 14 43 21" src="https://user-images.githubusercontent.com/22498435/114396111-7761c900-9b9d-11eb-8e9a-036b97f067de.png">

**Comment by Allan-Nava** [comment]
Strange problem when I try use Swift Package Manager:

When I compile locally the nakama sdk it works, but if I try to import from swift package manager:

<img width="1309" alt="Screenshot 2021-04-12 at 14 51 17" src="https://user-images.githubusercontent.com/22498435/114397189-b04e6d80-9b9e-11eb-9b33-ce3ef5800409.png">
<img width="246" alt="Screenshot 2021-04-12 at 14 51 27" src="https://user-images.githubusercontent.com/22498435/114397198-b3495e00-9b9e-11eb-8ec1-8ada5d6a1283.png">



The nakama sdk package manager it works 
![Screenshot 2021-04-12 at 14 51 33](https://user-images.githubusercontent.com/22498435/114397252-c3613d80-9b9e-11eb-8da0-d801c8d2677a.png)

**Comment by Allan-Nava** [comment]
fixe with swift package manager

**Comment by AllenNing181** [comment]
@Allan-Nava Still running issues with "GRPCCallHandler" not found.
Should I set locally to fix as well?

**Comment by Allan-Nava** [comment]
It is working: https://github.com/Allan-Nava/nakama-swift

Example to add the swift package manager: https://www.raywenderlich.com/7242045-swift-package-manager-for-ios#toc-anchor-001
