### ISSUE TITLE
Fatal error force unwrapping a variable

### ISSUE THREAD

**Issue by bazscott** [heroiclabs/nakama-swift#5]
When I call the `SelfFetchMessage` to fetch user data I get the following error:
`Fatal error: Unexpectedly found nil while unwrapping an Optional value`

I think the following line is at fault:
`self.socket!.write(data: payload!)` line 392 in Client.swift

The variable `socket` is nil, so causes a fatal error when force unwrapped.

**Comment by bazscott** [comment]
Sorry, closing this issue as I hadn't connected the client to the server correctly :)
For anyone in the future who has the same issue be sure to follow the *full* example code on how to connect session and client when logging in.

**Comment by mofirouz** [comment]
No problem :)
