### ISSUE TITLE
Update to support Nakama 2

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-swift#6]
Please leave a comment (or reaction) if you'd like us to update this client to Nakama 2.

**Comment by meganegora** [comment]
Yes +1

**Comment by mort3m** [comment]
Yes 👍

**Comment by marekkovac24** [comment]
yes

**Comment by CeMcK** [comment]
Yes please 👍

**Comment by brunodornelesbr** [comment]
yes

**Comment by amradawi** [comment]
That will be wonderful

**Comment by siamakf** [comment]
This would be super helpful!

**Comment by Kaspik** [comment]
Please! :)

**Comment by mofirouz** [comment]
@amradawi and @siamakf have kindly been working on the update of Nakama-Swift to 4.2 and Nakama 2.0. I'm working with them and will provide an update to the repo soon :)

**Comment by jmdecombe** [comment]
hi, i am very interested in the Swift 4.2 client for Nakama 2. i just discovered your product and want to use it for a new game. any update on availability? thanks.

**Comment by novabyte** [comment]
Thanks for the interest @jmdecombe. @mofirouz What is left to be done for this issue? Do we need to regenerate the GRPC stubs for the client code?

**Comment by mofirouz** [comment]
@jmdecombe and @novabyte - The client code that is on `master` has most of the functionality of Nakama 2 server (thanks to @amradawi for this excellent support!). However, there are some missing features and naming/design scheme updates that I'd like to do to the code at some point. You can use the code now but be aware that upon an official release, function signatures and input/output params may be different.

**Comment by jmdecombe** [comment]
@novabyte and @mofirouz ... thank you for the update, much appreciated. Good to know that the client works as is already. As for the improvements planned for the official release, would you mind sharing some approximate date for that official release? I know this date is bound to change, but I am just trying to get a general idea. Thank you.

**Comment by mofirouz** [comment]
@jmdecombe I think it would be best to speak over [Gitter](https://gitter.im/heroiclabs/nakama). Feel free to PM there and we can talk more specifics.

**Comment by meganegora** [comment]
Trying to use this now but my pod file can't find pod 'Nakama', '~> 2.0' when i try pod install...nakama 0.3 is found if i don't specify a version.

**Comment by ymoussaba** [comment]
Yes please

**Comment by nesimtunc** [comment]
Please update your documents for iOS. They're outdate and not compilable anymore. Thanks.

**Comment by nesimtunc** [comment]
When do you plan to release your iOS SDK for Nakama 2?

**Comment by Allan-Nava** [comment]
Yes please

**Comment by mofirouz** [comment]
The low-level client library (gRPC as well as realtime socket) has been updated to support Nakama 2 and Nakama 3. There are many gRPC wrapper functions missing from the implementation. Help is appreciated on this. I will close this in favor of #10.
