### ISSUE TITLE
Simulator support

### ISSUE THREAD

**Issue by jaischeema** [heroiclabs/nakama-swift#9]
Hi,

I am trying to use this library in an iOS project but have been getting issues regarding the libnghttp2 library not being compiled/available for the simulator. Has anybody got any recommendations on how can I get it working or if this is even supported on the simulator?

Cheers

**Comment by mofirouz** [comment]
We don't use libnghttp2 anywhere in the codebase. Additionally we've pushed a major update to use Swift 5. Please update to the latest and let us know if you still have issues with simulators - they should be fully supported.
